title = "ft_package"

[project]
Name = "ft_package"
Version = "0.0.1"
Summary = "I did this only because THEY asked me to do it, I hope THEY'll be happy with it"
Home-page = ""
Author = ""
Author-email = ""
License = ""
Location = ""
Requires = ""
Required-by = ""
Metadata-Version = ""
Installer = ""
Classifiers = ""
Entry-points = ""